/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          primary: '#FFCD00',
          secondary: '#002395',
          dark: {
            DEFAULT: '#020817',
            100: '#041432',
            200: '#001a70',
            300: '#0A1229',
            400: '#05111F',
            500: '#081729',
          },
          accent: '#C26B78',
          white: '#ffffff',
          muted: 'rgba(255, 255, 255, 0.6)',
        },
      },
      fontFamily: {
        serif: ['Inria Serif', 'serif'],
        sans: ['Barlow', 'sans-serif'],
      },
      fontSize: {
        'h1-mobile': '40px',
        'h1-tablet': '56px',
        'h1-desktop': '80px',
        'h1-wide': '104px',
        'h2-mobile': '32px',
        'h2-tablet': '48px',
        'h2-desktop': '64px',
        'h3-mobile': '28px',
        'h3-tablet': '36px',
        'h3-desktop': '42px',
        'h4-mobile': '22px',
        'h4-tablet': '28px',
        'h4-desktop': '32px',
        'h5-mobile': '18px',
        'h5-tablet': '22px',
        'h5-desktop': '26px',
        'lead-mobile': '16px',
        'lead-tablet': '18px',
        'lead-desktop': '18px',
        'body': '16px',
      },
      lineHeight: {
        'h1': '1.1',
        'h2': '1.2',
        'h3': '1.3',
        'h4': '1.4',
        'h5': '1.5',
        'lead': '1.7',
        'body': '1.6',
      },
      spacing: {
        'section-mobile': '60px',
        'section-tablet': '80px',
        'section-desktop': '120px',
      },
      screens: {
        'xs': '480px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1440px',
        '3xl': '1920px',
      },
    },
  },
  plugins: [],
};
